module.exports = {
    MappingJordan,
    MappingNike,
    MappingAdidas,
    MappingAll
}
function MappingAll( str ){

    str = str.replace("Boat", "보트")
    str = str.replace("Decon", "데콘")
    str = str.replace("Legend", "레전드")
    str = str.replace("New", "뉴")

    str = str.replace("Slip-On", "슬립온")
    str = str.replace("Slip On", "슬립온")
    str = str.replace("Pro", "프로")
    str = str.replace("Slip", "슬립온")
    str = str.replace("Alpha", "알파")
    str = str.replace("ACE", "에이스")
    str = str.replace("Ace", "에이스")
    str = str.replace("Max", "맥스")
    str = str.replace("Trek", "트렉")
    str = str.replace("Team", "팀")
    str = str.replace("Origin", "오리진")
    str = str.replace("Premiere", "프리미어")
    str = str.replace("Premium", "프리미엄")

    str = str.replace("Christmas", "크리스마스")
    str = str.replace("Leather", "레더")
    str = str.replace("Suede", "스웨이드")
    str = str.replace("Recon", "레콘")
    str = str.replace("Craft", "크레프트")
    str = str.replace("Buckle", "버클")
    str = str.replace("Trail", "트레일")
    str = str.replace("Trainers", "트레이너")
    str = str.replace("Trainer", "트레이너")
    str = str.replace("Train", "트레인")
    str = str.replace("Running", "러닝")
    str = str.replace("Runner", "러너")
    str = str.replace("Run", "런")
    str = str.replace("Racing", "레이싱")
    str = str.replace("Racer", "레이서")
    str = str.replace("Nova", "노바")
    str = str.replace("Skate", "스케이트")
    str = str.replace("Support", "서포트")
    str = str.replace("Boost", "부스트")
    str = str.replace("Super", "슈퍼")
    str = str.replace("Pack", "팩")
    str = str.replace("High", "하이")
    str = str.replace("Mid", "미드")
    str = str.replace("Low", "로우")
    str = str.replace("Retro", "레트로")

    return str

}
function MappingJordan ( str ){
        str = str.replace("Jordan Jordan", "Jordan")
        str = str.replace("Air Jordan", "조던")
		str = str.replace("Jordan", "조던")
		str = str.replace("Spizike","스피자이크")
		str = str.replace("Flightclub","플라이트클럽")
		str = str.replace("Flight","플라이트")
        

		str = str.replace("Nouveau", "누보")
		str = str.replace("Formula", "포뮬러")
		str = str.replace("Future", "퓨처")

		str = str.replace("Jumpman", "점프맨")
		str = str.replace("LStyle", "엘스타일")
		str = str.replace("Pure", "퓨어")

		str = str.replace("Flyknit", "플라이니트")
		str = str.replace("Super.Fly", "슈퍼플라이")
		str = str.replace("Super Fly", "슈퍼플라이")
		str = str.replace("Super", "슈퍼")
		str = str.replace("Prime.Fly", "프라임 플라이")
		str = str.replace("Prime", "프라임")
		str = str.replace("Fly", "플라이")
		str = str.replace("Hydro", "하이드로")
        str = str.replace("Advance", "어드밴스")
        str = str.replace("Ultra", "울트라")
        str = str.replace("Express", "익스프레스")
        str = str.replace("Melo", "멜로")
		str = str.replace("Imminent", "이미넌트")
		str = str.replace("Illusion", "일루전")
        
		str = str.replace("School", "스쿨")
		str = str.replace("Velocity", "벨로시티")
		str = str.replace("Trainer", "트레이너")
		str = str.replace("Train", "트레인")
		str = str.replace("Air", "에어")
        //console.log(`${array[0]}. ${input[i].shoe} \t=> ${str}`)


		str = str.replace("XXXIII", "33")
		str = str.replace("XXXII", "32")
		str = str.replace("XXXI", "31")

		str = str.replace("XXX3", "33")
		str = str.replace("XXX2", "32")
		str = str.replace("XXX1", "31")
	
		str = str.replace("XXX", "30")
		str = str.replace("XX9", "29")
		str = str.replace("XX8", "28")
		str = str.replace("XX", "20")

		str = str.replace("Xiii", "13")
		str = str.replace("Xii", "12")
		str = str.replace("XI", "11")
		str = str.replace("Xi", "11")


		str = str.replace("VIII", "8")
		str = str.replace("Viii", "8")
		str = str.replace("VII", "7")
		str = str.replace("VI", "6")
		str = str.replace("IV 4", "4")
			
		str = str.replace("V.", "5.")
		str = str.replace(" V", " 5")
		str = str.replace("I 1", "1")
		str = str.replace("III", "3")
        str = str.replace("II", "2")
        return str
}

function MappingNike ( str ){
    str = str.replace("Nike", "나이키")
    str = str.replace("Air Max", "에어맥스")
    str = str.replace("Air Force", "에어포스")
    str = str.replace("Delta Force", "델타포스")
    str = str.replace("Sky Force", "스카이포스")
    str = str.replace("Court Force", "코트포스")
    str = str.replace("Lunar Force", "루나포스")

    str = str.replace("HyperRev", "하이퍼레브")
    str = str.replace("Hyperrev", "하이퍼레브")
    str = str.replace("HyperAdapt", "하이퍼어댑트")
    str = str.replace("Hypershift", "하이퍼쉬프트")
    str = str.replace("Hypervenom", "하이퍼베놈")
    str = str.replace("Hyperdunk", "하이퍼덩크")
    str = str.replace("Hyperize", "하이퍼라이즈")
    str = str.replace("Hyperfuse", "하이퍼퓨즈")
    str = str.replace("Hyperlive", "하이퍼라이브")
    str = str.replace("Hyperchase", "하이퍼체이스")
    str = str.replace("Hyperflight", "하이퍼플라이트")
    str = str.replace("Hyperquickness", "하이퍼퀵니스")
    str = str.replace("Hyperposite", "하이퍼포짓")
    str = str.replace("Hyperfeel", "하이퍼필")

    str = str.replace("Lunar Epic", "루나에픽")
    str = str.replace("LunarEpic", "루나에픽")
    str = str.replace("Lunarepic", "루나에픽")
    str = str.replace("LunarSolo", "루나솔로")
    str = str.replace("Lunarendor", "루나엔도어")
    str = str.replace("Lunartempo", "루나템포")
    str = str.replace("Lunardome", "루나돔")
    str = str.replace("Lunarcharge", "루나차지")
    str = str.replace("Lunar", "루나")
    str = str.replace("Lupinek", "루피넥")

    str = str.replace("Superfly", "슈퍼플라이")
    str = str.replace("Mayfly", "메이플라이")
    str = str.replace("Vaporfly", "베이퍼플라이")
    str = str.replace("VaporMax", "베이퍼맥스")
    str = str.replace("Flystepper", "플라이스테퍼")
    str = str.replace("Flyknit", "플라이니트")
    str = str.replace("Flightposite", "플라이트포짓")
    str = str.replace("Foamposite", "폼포짓")
    str = str.replace("Flight", "플라이트")
    str = str.replace("Posite", "포짓")
    str = str.replace("Fly", "플라이")
    str = str.replace("Sky", "스카이")

    str = str.replace("Waffle Racer", "와플레이서")
    str = str.replace("Waffle", "와플")
    str = str.replace("Aqua Sock", "아쿠아삭")
    str = str.replace("Sock Racer", "삭레이서")
    str = str.replace("Sock Dart", "삭다트")
    str = str.replace("Moon Racer", "문레이서")
    str = str.replace("Moon", "문")

    str = str.replace("Stefan Janoski", "스테판 야노스키")
    str = str.replace("Janoski", "야노스키")
    str = str.replace("Paul Rodriguez", "폴 로드리게즈")
    str = str.replace("Cradle Rock", "크래들락")
    str = str.replace("Blazer", "블레이저")
    str = str.replace("Supreme", "슈프림")
    str = str.replace("Trainerendor", "트레이너엔도르")
    str = str.replace("Trainer", "트레이너")
    str = str.replace("Train", "트레인")
    str = str.replace("LeBron", "르브론")
    str = str.replace("Mogan", "모건")
    str = str.replace("Vomero", "보메로")
    str = str.replace("Romaleos", "로말레오")
    str = str.replace("Odyssey", "오디세이")
    str = str.replace("Loden", "로덴")
    str = str.replace("Deconstructed", "디컨스트럭티드")

    str = str.replace("Free Run", "프리런")
    str = str.replace("Free RN", "프리런")
    str = str.replace("Free", "프리")

    str = str.replace("Portmore", "포트모어")
    str = str.replace("Solarsoft", "솔라소프트")
    str = str.replace("Pocket Knife", "포켓나이프")
    str = str.replace("Pocketknife", "포켓나이프")

    str = str.replace("Metcon", "메트콘")
    str = str.replace("Lil Penny", "릴페니")
    str = str.replace("Penny", "페니")
    str = str.replace("Mamba Rage", "맘바 레이지")
    str = str.replace("Mamba", "맘바")
    str = str.replace("Roshe Run", "로쉐런")    //물어보기
    str = str.replace("Rosherun", "로쉐런")
    str = str.replace("Roshe One", "로쉬 원")
    str = str.replace("Roshe", "로쉬")
    str = str.replace("Bruin", "브루인")
    str = str.replace("Gato", "가토")
    str = str.replace("Toki", "토키")
    str = str.replace("Kyrie", "카이리")
    str = str.replace("Cortez", "코르테즈")
    str = str.replace("Nano", "나노")
    str = str.replace("Braata", "브라타")
    str = str.replace("Rookie", "루키")
    str = str.replace("Pippen", "피펜")
    str = str.replace("Huarache", "허라치")
    str = str.replace("Gaiter", "게이터")
    str = str.replace("Moccasin", "모카신")
    str = str.replace("Griffey", "그리피")
    str = str.replace("Voltak", "볼텍")
    str = str.replace("Vortax", "볼텍스")
    str = str.replace("Tanjun", "탄준")
    str = str.replace("Benassi", "베나시")
    str = str.replace("Phelon", "펠론")
    str = str.replace("Regime", "레짐")

    str = str.replace("All Court", "올코트")
    str = str.replace("Superdome", "슈퍼돔")
    str = str.replace("Squad", "스쿼드")
    str = str.replace("React", "리엑트")
    str = str.replace("Element", "엘리먼트")
    str = str.replace("Royal", "로얄")
    str = str.replace("Sonic", "소닉")
    str = str.replace("Encore", "온코어")
    str = str.replace("Soldier", "솔져")
    str = str.replace("Mercurial", "머큐리얼")
    str = str.replace("Vapor", "베이퍼")
    str = str.replace("Vandal", "반달")
    str = str.replace("Zoom", "줌")
    str = str.replace("Air", "에어")
    str = str.replace("Alpha", "알파")
    str = str.replace("Kobe", "코비")
    str = str.replace("Dunk", "덩크")
    str = str.replace("Hybrid", "하이브리드")
    str = str.replace("Shox", "샥스")
    str = str.replace("Canvas", "캔버스")
    str = str.replace("Total", "토탈")
    str = str.replace("Untouchable", "언터쳐블")
    str = str.replace("Presto", "프레스토")
    str = str.replace("Gravity", "그레비티")
    str = str.replace("Killshot", "킬샷")
    str = str.replace("Vintage", "빈티지")  //중고??
    str = str.replace("Ultra", "울트라")
    str = str.replace("Rise", "라이즈")
    str = str.replace("Rebel", "레벨")
    str = str.replace("Adapt", "어댑트")
    str = str.replace("Control", "컨트롤")
    str = str.replace("Woven", "우븐")
    str = str.replace("Duel", "듀얼")
    str = str.replace("Basic", "베이직")
    str = str.replace("Tennis", "테니스")
    str = str.replace("Classic", "클래식")
    str = str.replace("Studio", "스튜디오")
    str = str.replace("Two", "2")
    return str
}


function MappingAdidas ( str ){
    str = str.replace("adidas", "아디다스")
    str = str.replace("Yeezy Boost", "이지부스트")
    str = str.replace("Yeezy", "이지")
    str = str.replace("Ultra Boost", "울트라부스트")
    str = str.replace("Ultraboost", "울트라부스트")
    str = str.replace("Energy Boost", "에너지부스트")
    str = str.replace("Solarboost", "솔라부스트")
    str = str.replace("Pure Boost", "퓨어부스트")
    str = str.replace("PureBoost", "퓨어부스트")
    str = str.replace("Pureboost", "퓨어부스트")
    str = str.replace("Purebounce", "퓨어바운스")
    str = str.replace("Purecontrol", "퓨어컨트롤")
    str = str.replace("PureControl", "퓨어컨트롤")
    str = str.replace("Marquee Boost", "마키부스트")
    str = str.replace("Busenitz", "부세니츠")
    str = str.replace("Harden", "하든")
    str = str.replace("Iniki", "이니키")
    str = str.replace("Nemeziz", "네메시스")
    str = str.replace("Spezial", "스페지알")
    str = str.replace("Superstar", "슈퍼스타")
    str = str.replace("Supernova", "수퍼노바")
    str = str.replace("Alphaedge", "알파엣지")
    str = str.replace("Stan Smith", "스탠스미스")

    str = str.replace("CrazyTrain", "크레이지 트레인")
    str = str.replace("Crazy Light", "크레이지 라이트")
    str = str.replace("Crazylight", "크레이지 라이트")
    str = str.replace("Crazy", "크레이지")
    

    str = str.replace("Instinct", "인스팅트")
    str = str.replace("Response", "리스판스")   //리스폰스로도 많이나옴
    str = str.replace("Chop Shop", "찹샵")
    str = str.replace("Haven", "헤븐")
    str = str.replace("Copa", "코파")
    str = str.replace("COPA", "코파")
    str = str.replace("Qasa", "콰사")   //카사
    str = str.replace("Slingshot", "슬링샷")
    str = str.replace("Hulton", "헐튼")
    str = str.replace("Mundial", "문디알")
    str = str.replace("Kozoko", "코조코")
    str = str.replace("JawPaw", "조포")
    str = str.replace("Aktiv", "악티브")
    str = str.replace("Tango", "탱고")
    str = str.replace("Nizza", "니짜")
    str = str.replace("Elle", "엘르")
    str = str.replace("Garwen", "가윈")
    str = str.replace("Lacombe", "라콤베")
    str = str.replace("Ozweego", "오즈위고")
    str = str.replace("Tubular", "튜블라")
    str = str.replace("Glenbuck", "글렌벅")
    str = str.replace("Rascal", "라스칼")
    str = str.replace("Speedfactory", "스피드 팩토리")

    str = str.replace("adiColor", "아디컬러")
    str = str.replace("Adicolor", "아디컬러")
    str = str.replace("Adizero", "아디제로")
    str = str.replace("adiZero", "아디제로")
    str = str.replace("Afterburner", "에프터버너")



    str = str.replace("Hypersleek", "하이퍼슬릭")
    str = str.replace("Sleek", "슬릭")
    str = str.replace("Shadow", "섀도우")
    str = str.replace("Berlin", "베를린")
    str = str.replace("Boston", "보스턴")
    str = str.replace("Predator", "프레데터")
    str = str.replace("Accelerator", "엑셀레이터")

    str = str.replace("Futurepacer", "퓨처페이서")
    str = str.replace("Futurecraft", "퓨처크래프트")
    str = str.replace("Stockholm", "스톡홀름")
    str = str.replace("Torsion", "토션")
    str = str.replace("Terrex", "테렉스")
    str = str.replace("Gazelle", "가젤")
    str = str.replace("Climacool", "클라이마쿨")    //클리마도 씀
    str = str.replace("ClimaCool", "클라이마쿨")    //클리마도 씀
    str = str.replace("Sambarose", "삼바로즈")
    str = str.replace("Samba", "삼바")
    str = str.replace("AlphaBounce", "알파바운스")
    str = str.replace("Alphabounce", "알파바운스")
    str = str.replace("Roundhouse", "라운드하우스")
    str = str.replace("Campus", "캠퍼스")
    str = str.replace("Hardland", "하드랜드")
    str = str.replace("Century", "센츄리")
    str = str.replace("Mad Clima", "매드 클라이마")
    str = str.replace("Marathon", "마라톤")
    str = str.replace("Powerphase", "파워페이즈")
    str = str.replace("Solar", "솔라")
    str = str.replace("Explosive", "익스플로시브")


    str = str.replace("Lightswitch", "라이트스위치")
    str = str.replace("Gil", "길")
    str = str.replace("Replicant", "레플리카")
    str = str.replace("Micropacer", "마이크로페이서")
    str = str.replace("Primeknit", "프라임니트")
    str = str.replace("Climacool", "클라이마쿨")
    str = str.replace("Clima", "클라이마")

    str = str.replace("Cloudfoam", "클라우드폼")
    str = str.replace("Indoor", "인도어")
    str = str.replace("Kreft", "크래프트")
    str = str.replace("Advantage", "어드벤티지")
    str = str.replace("Clean", "클린")
    str = str.replace("Level", "레벨")
    str = str.replace("Bunny", "버니")
    str = str.replace("Icon", "아이콘")
    str = str.replace("Turf", "터프")
    str = str.replace("Ultimate", "얼티메이트")
    str = str.replace("Modern", "모던")
    str = str.replace("Daily", "데일리")
    

    return str
}