module.exports = [
    'Air Jordan Five',
    'Air Jordan Two',
    'Air Jordan Spizike',
    'Air Jordan Packs',
    'adidas Other',
    'Air Jordan Ten',
    'Air Jordan Four ',
    'Air Jordan One',
    'Air Jordan Twenty ',
    'Air Jordan Twelve ',
    'Air Jordan Other',
    'Air Jordan Eleven ',
    'Vans',
    'Air Max 95',
    'Air Max One ',
    'Air Max 90',
    'Air Jordan Sixteen',
    'Air Jordan Seventeen',
    'Air Jordan Fourteen ',
    'Air Jordan Nineteen ',
    'Other ',
    'Air Jordan Six',
    'Nike Basketball Penny ',
    'Nike Basketball Dunk Low',
    'Air Jordan Three',
    'Nike Basketball Other ',
    'Air Jordan Seven',
    'Converse',
    'Air Jordan Thirteen ',
    'KD Three',
    'KD One',
    'KD Two',
    'Nike Running Other',
    'Saucony ',
    'Air Jordan Twenty-Nine',
    'Li Ning ',
    'Reebok',
    'Foamposite Other',
    'Foamposite Pro',
    'Air Jordan Eighteen ',
    'New Balance ',
    'Kobe One',
    'Kobe Two',
    'Air Max Other ',
    'Air Max 1 ',
    'Foamposite One',
    'Nike SB Other ',
    'Nike SB SB Dunk High',
    'Nike SB SB Dunk Low ',
    'Nike SB Dunk Mid',
    'Nike SB Dunk Low',
    'Nike SB Dunk High ',
    'Asics ',
    'Puma',
    'Air Force One ',
    'Air Force Other ',
    'LeBron Other',
    'Nike Training Other ',
    'Diadora ',
    'Nike Basketball Dunk',
    'Nike Basketball Dunk High ',
    'Air Jordan Twenty-Three ',
    'Air Jordan Nine ',
    'KD Twelve ',
    'KD Eleven ',
    'Air Max 97',
    'Air Jordan Eight',
    'Kobe Six',
    'Kobe Five ',
    'Air Jordan Thirty-Two ',
    'Under Armour',
    'Nike Basketball Kyrie ',
    'Nike Other Other',
    'Nike SB Janoski ',
    'Air Max 98',
    'Air Max 93',
    'Air Jordan Fifteen',
    'Air Max Zero',
    'LeBron Nine ',
    'LeBron Eight',
    'Kobe Eight',
    'Kobe Seven',
    'KD Six',
    'Nike SB SB Dunk Mid ',
    'KD Five ',
    'Louis Vuitton ',
    'Air Max VaporMax',
    'Air Max 720 ',
    'Kobe Other',
    'LeBron Seven',
    'KD Ten',
    'KD Other',
    'KD Nine ',
    'LeBron Ten',
    'adidas Iniki',
    'Nike Basketball Hyperdunk ',
    'Nike Basketball Barkley ',
    'KD Four ',
    'Kobe Ten',
    'Kobe Nine ',
    'Nike Basketball Zoom Rookie ',
    'Nike Basketball Flight One',
    'LeBron Fifteen',
    'Air Jordan Twenty-Eight ',
    'LeBron Zoom Soldier ',
    'LeBron One',
    'LeBron Soldier',
    'adidas NMD',
    'Air Max 180 ',
    'LeBron Five ',
    'Air Jordan Twenty-One ',
    'Kobe Eleven ',
    'Kobe Fade to Black',
    'Kobe Prelude',
    'Kobe 9',
    'Air Jordan Thirty ',
    'Air Jordan Thirty-Three ',
    'adidas Yeezy',
    'Kobe Three',
    'Air Jordan Thirty-One ',
    'Kobe Four ',
    'KD Eight',
    'LeBron Three',
    'LeBron Two',
    'LeBron Six',
    'LeBron Thirteen ',
    'LeBron Twelve ',
    'LeBron Eleven ',
    'LeBron Sixteen',
    'KD Seven',
    'adidas Ultra Boost',
    'Nike Other',
    'Air Max Plus',
    'Nike Air Max',
    'Air Jordan Twenty-Two ',
    'Kobe A.D',
    'Kobe A.D. ',
    'Kobe AD ',
    'LeBron Four ',
    'Air Force 1 ',
    'LeBron Fourteen ',
    'Air Force High',
    'Air Force Two ',
    'Nike Running Air Max'
]